### PR TITLE
Make psyrcd installable

### PR DESCRIPTION
**Pull request by barnumbirr**
- added main() function for setup entrypoint
- added setup.py file
- moved TODO to file
- moved LICENSE to file
- improved README

As _psyrcd_ still uses hardcoded settings it makes little to no sense to install it for now. PR with config file
is coming up soon. :grinning:

### CODE REVIEW

**Comment by barnumbirr** [comment]
@LukeB42 don't merge this yet, I've just found out that this doesn't copy psyrcd/scripts to /usr/local/bin/.
Will have to figure out the best way to make this work...

**Comment by float64co** [comment]
Could install it as a module and have init scripts do "python -m psyrcd --option=value"
Could make the default value for the scripts directory ~/.psyrcd/scripts or "psyrcd.scripts" where the scripts dir is just relative to where psyrcd is installed to

**Comment by barnumbirr** [comment]
We could also ditch setuptools and create an install script like most IRCds use. Would allow the users to install wherever they want.

**Comment by float64co** [comment]
Ok feel free to submit anything as a feature branch

**Pull request closed without merging**
